from app.models.enums import UserRole


ROLE_PERMISSIONS: dict[UserRole, set[str]] = {
    UserRole.SUPERADMIN: {
        "superadmin:access",
    },
    UserRole.OWNER: {
        "employees:read",
        "employees:write",
        "schedules:read",
        "schedules:write",
        "attendance:read",
        "attendance:write",
        "attendance:manage",
        "metrics:read",
        "tickets:read",
        "tickets:write",
        "exports:read",
        "locations:read",
        "locations:write",
        "settings:read",
        "settings:write",
        "salary:read",
        "salary:manage",
        "users:manage",
        "users:read",
        "users:write",
        "expense_tickets:read",
        "expense_tickets:write",
        "expense_tickets:approve",
        "expense_tickets:export",
        "late_arrivals:read",
        "late_arrivals:manage",
        "late_arrivals:export",
        "cash_closures:read",
        "cash_closures:write",
        "cash_closures:manage",
        "cash_closures:analytics",
        "cash_closures:export",
        "board:read",
        "board:write",
        "gdpr:export",
    },
    UserRole.ADMIN: {
        "employees:read",
        "employees:write",
        "schedules:read",
        "schedules:write",
        "attendance:read",
        "attendance:write",
        "attendance:manage",
        "metrics:read",
        "tickets:read",
        "tickets:write",
        "exports:read",
        "locations:read",
        "locations:write",
        "settings:read",
        "settings:write",
        "salary:read",
        "salary:manage",
        "users:manage",
        "users:read",
        "users:write",
        "expense_tickets:read",
        "expense_tickets:write",
        "expense_tickets:approve",
        "expense_tickets:export",
        "late_arrivals:read",
        "late_arrivals:manage",
        "late_arrivals:export",
        "cash_closures:read",
        "cash_closures:write",
        "cash_closures:manage",
        "cash_closures:analytics",
        "cash_closures:export",
        "board:read",
        "board:write",
        "gdpr:export",
    },
    UserRole.HR_MANAGER: {
        "employees:read",
        "employees:write",
        "attendance:read",
        "attendance:manage",
        "metrics:read",
        "tickets:read",
        "tickets:write",
        "exports:read",
        "salary:read",
        "salary:manage",
        "users:read",
        "users:write",
        "expense_tickets:read",
        "expense_tickets:write",
        "expense_tickets:approve",
        "expense_tickets:export",
        "late_arrivals:read",
        "late_arrivals:manage",
        "late_arrivals:export",
        "board:read",
        "board:write",
    },
    UserRole.MANAGER: {
        "employees:read",
        "schedules:read",
        "attendance:read",
        "attendance:write",
        "attendance:manage",
        "metrics:read",
        "tickets:read",
        "tickets:write",
        "locations:read",
        "expense_tickets:read",
        "expense_tickets:write",
        "expense_tickets:approve",
        "late_arrivals:read",
        "late_arrivals:manage",
        "cash_closures:read",
        "cash_closures:write",
        "board:read",
        "board:write",
    },
    UserRole.EMPLOYEE: {
        "attendance:read",
        "attendance:write",
        "tickets:read",
        "tickets:write",
        "expense_tickets:read",
        "expense_tickets:write",
        "late_arrivals:read",
    },
}

# Roles that can access tenant administration features.
ADMIN_ROLES = {UserRole.OWNER, UserRole.ADMIN, UserRole.HR_MANAGER, UserRole.MANAGER}


def permissions_for_role(role: UserRole) -> list[str]:
    return sorted(ROLE_PERMISSIONS.get(role, set()))


def role_has_permission(role: UserRole, permission: str) -> bool:
    return permission in ROLE_PERMISSIONS.get(role, set())


def is_admin_role(role: UserRole) -> bool:
    return role in ADMIN_ROLES
