from datetime import datetime

from app.config import DEFAULT_ADMIN_PASSWORD, DEFAULT_ADMIN_USERNAME
from app.database.connection import get_connection
from app.database.sql import normalize_datetime
from app.utils.security import hash_password, verify_password


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT,
    full_name TEXT,
    google_id TEXT,
    auth_provider TEXT NOT NULL DEFAULT 'password'
        CHECK (auth_provider IN ('password', 'google')),
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    dni TEXT NOT NULL,
    password_hash TEXT,
    role TEXT NOT NULL DEFAULT 'employee'
        CHECK (role IN ('admin', 'employee')),
    platform_role TEXT
        CHECK (platform_role IS NULL OR platform_role IN ('superadmin', 'internal_admin')),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    force_password_change BOOLEAN NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMP WITHOUT TIME ZONE,
    deactivated_at TIMESTAMP WITHOUT TIME ZONE,
    last_business_id TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS businesses (
    id TEXT PRIMARY KEY,
    owner_user_id INTEGER NOT NULL,
    name TEXT,
    business_name TEXT NOT NULL,
    business_type TEXT NOT NULL,
    primary_email TEXT,
    phone TEXT,
    timezone TEXT NOT NULL DEFAULT 'Europe/Madrid',
    country TEXT,
    login_code TEXT NOT NULL,
    slug TEXT NOT NULL,
    business_key TEXT NOT NULL,
    settings_json TEXT NOT NULL DEFAULT '{}',
    last_accessed_at TIMESTAMP WITHOUT TIME ZONE,
    suspended_at TIMESTAMP WITHOUT TIME ZONE,
    suspended_reason TEXT,
    archived_at TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_dni_lower
ON users(LOWER(dni));

CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_login_code_active
ON businesses(LOWER(login_code))
WHERE is_active IS TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_slug
ON businesses(slug);

CREATE UNIQUE INDEX IF NOT EXISTS idx_businesses_business_key
ON businesses(business_key);

CREATE INDEX IF NOT EXISTS idx_businesses_owner
ON businesses(owner_user_id);

CREATE TABLE IF NOT EXISTS business_members (
    business_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    member_role TEXT NOT NULL DEFAULT 'employee'
        CHECK (member_role IN ('owner', 'admin', 'employee')),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    joined_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_accessed_at TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY (business_id, user_id),
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_business_members_user
ON business_members(user_id, is_default, last_accessed_at);

CREATE INDEX IF NOT EXISTS idx_business_members_business
ON business_members(business_id, member_role);

CREATE TABLE IF NOT EXISTS business_users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    role TEXT NOT NULL
        CHECK (role IN ('owner', 'admin', 'manager', 'employee', 'kiosk_device')),
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('active', 'invited', 'disabled')),
    invited_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (business_id, user_id),
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_business_users_user
ON business_users(user_id, status);

CREATE INDEX IF NOT EXISTS idx_business_users_business
ON business_users(business_id, role, status);

CREATE TABLE IF NOT EXISTS plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    max_employees INTEGER NOT NULL,
    max_admins INTEGER NOT NULL,
    has_kiosk BOOLEAN NOT NULL DEFAULT TRUE,
    has_advanced_reports BOOLEAN NOT NULL DEFAULT FALSE,
    has_geolocation BOOLEAN NOT NULL DEFAULT FALSE,
    has_multi_location BOOLEAN NOT NULL DEFAULT FALSE,
    has_exports_basic BOOLEAN NOT NULL DEFAULT TRUE,
    has_exports_advanced BOOLEAN NOT NULL DEFAULT FALSE,
    has_filters_advanced BOOLEAN NOT NULL DEFAULT FALSE,
    has_incident_management BOOLEAN NOT NULL DEFAULT FALSE,
    has_admin_closures BOOLEAN NOT NULL DEFAULT FALSE,
    has_implementation_support BOOLEAN NOT NULL DEFAULT FALSE,
    has_priority_support BOOLEAN NOT NULL DEFAULT FALSE,
    has_custom_branding BOOLEAN NOT NULL DEFAULT FALSE,
    price_monthly NUMERIC(10, 2) NOT NULL DEFAULT 0,
    price_yearly NUMERIC(10, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT NOT NULL UNIQUE,
    plan_id INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'active'
        CHECK (status IN ('trial', 'trialing', 'active', 'past_due', 'paused', 'cancelled', 'canceled', 'expired', 'suspended', 'incomplete')),
    billing_cycle TEXT NOT NULL DEFAULT 'monthly'
        CHECK (billing_cycle IN ('monthly', 'yearly')),
    price NUMERIC(10, 2),
    currency TEXT NOT NULL DEFAULT 'EUR',
    current_period_start TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    current_period_end TIMESTAMP WITHOUT TIME ZONE,
    renewal_date TIMESTAMP WITHOUT TIME ZONE,
    cancel_at TIMESTAMP WITHOUT TIME ZONE,
    cancelled_at TIMESTAMP WITHOUT TIME ZONE,
    trial_ends_at TIMESTAMP WITHOUT TIME ZONE,
    paused_at TIMESTAMP WITHOUT TIME ZONE,
    payment_status TEXT NOT NULL DEFAULT 'none',
    notes TEXT,
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (plan_id) REFERENCES plans(id)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_plan
ON subscriptions(plan_id, status);

CREATE TABLE IF NOT EXISTS payment_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT NOT NULL,
    subscription_id INTEGER,
    provider TEXT NOT NULL DEFAULT 'internal',
    external_id TEXT,
    amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'EUR',
    status TEXT NOT NULL DEFAULT 'estimated',
    billing_period_start TIMESTAMP WITHOUT TIME ZONE,
    billing_period_end TIMESTAMP WITHOUT TIME ZONE,
    paid_at TIMESTAMP WITHOUT TIME ZONE,
    due_at TIMESTAMP WITHOUT TIME ZONE,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (subscription_id) REFERENCES subscriptions(id)
);

CREATE INDEX IF NOT EXISTS idx_payment_records_business
ON payment_records(business_id, created_at DESC);

CREATE TABLE IF NOT EXISTS audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id INTEGER,
    actor_email TEXT,
    action TEXT NOT NULL,
    resource_type TEXT,
    resource_id TEXT,
    business_id TEXT,
    old_value TEXT,
    new_value TEXT,
    metadata TEXT,
    ip_address TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (actor_user_id) REFERENCES users(id),
    FOREIGN KEY (business_id) REFERENCES businesses(id)
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_created
ON audit_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_audit_logs_business
ON audit_logs(business_id, created_at DESC);

CREATE TABLE IF NOT EXISTS platform_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    user_id INTEGER NOT NULL,
    clock_in_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    clock_out_time TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    total_seconds INTEGER,
    notes TEXT,
    exit_note TEXT,
    incident_type TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_by_admin BOOLEAN NOT NULL DEFAULT FALSE,
    manual_close_reason TEXT,
    closed_by_user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_user_clock_in
ON attendance_sessions(user_id, clock_in_time);

CREATE INDEX IF NOT EXISTS idx_attendance_sessions_clock_in
ON attendance_sessions(clock_in_time);

CREATE TABLE IF NOT EXISTS employees (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    user_id INTEGER,
    internal_code TEXT,
    pin_code TEXT,
    first_name TEXT,
    last_name TEXT,
    name TEXT NOT NULL,
    username TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'employee'
        CHECK (role IN ('admin', 'employee')),
    email TEXT,
    phone TEXT,
    role_title TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (business_id) REFERENCES businesses(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS time_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    employee_id INTEGER NOT NULL,
    entry_type TEXT NOT NULL
        CHECK (entry_type IN ('entrada', 'salida')),
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_username_lower
ON employees(LOWER(username));

CREATE INDEX IF NOT EXISTS idx_time_entries_employee_timestamp
ON time_entries(employee_id, timestamp);

CREATE INDEX IF NOT EXISTS idx_time_entries_timestamp
ON time_entries(timestamp);

CREATE TABLE IF NOT EXISTS work_schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id TEXT,
    name TEXT NOT NULL,
    description TEXT,
    weekly_hours_target REAL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS schedule_days (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id INTEGER NOT NULL,
    day_of_week SMALLINT NOT NULL,
    start_time TIME WITHOUT TIME ZONE NOT NULL,
    end_time TIME WITHOUT TIME ZONE NOT NULL,
    break_minutes SMALLINT NOT NULL DEFAULT 0,
    late_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
    early_leave_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
    UNIQUE (schedule_id, day_of_week),
    FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS employee_schedules (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    schedule_id INTEGER NOT NULL,
    business_id TEXT,
    effective_from DATE NOT NULL,
    effective_to DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_employee_schedules_user
ON employee_schedules(user_id, is_active);

CREATE INDEX IF NOT EXISTS idx_employee_schedules_schedule
ON employee_schedules(schedule_id);

CREATE TABLE IF NOT EXISTS employee_profiles (
    user_id INTEGER PRIMARY KEY,
    hire_date DATE,
    contract_type TEXT,
    department TEXT,
    job_title TEXT,
    phone TEXT,
    personal_email TEXT,
    emergency_contact_name TEXT,
    emergency_contact_phone TEXT,
    social_security_number TEXT,
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

"""


def initialize_database() -> None:
    with get_connection() as connection:
        connection.execute("SELECT pg_advisory_xact_lock(%s)", (2_026_041_400,))
        _execute_schema(connection)
        _migrate_users_saas_columns(connection)
        _migrate_platform_user_columns(connection)
        _migrate_business_saas_columns(connection)
        _migrate_business_platform_columns(connection)
        _migrate_business_foundation(connection)
        _migrate_business_users_table(connection)
        _migrate_plans_and_subscriptions(connection)
        _migrate_plans_add_feature_columns(connection)
        _migrate_subscription_platform_columns(connection)
        _migrate_payment_records_table(connection)
        _migrate_audit_logs_table(connection)
        _migrate_platform_settings_table(connection)
        _migrate_employees_saas_columns(connection)
        _migrate_legacy_employee_columns(connection)
        _migrate_users_from_legacy_employees(connection)
        _ensure_default_admin(connection)
        _demote_legacy_default_admin_platform_role(connection)
        _sync_users_to_legacy_employees(connection)
        _sync_business_members_to_business_users(connection)
        _ensure_subscriptions_for_existing_businesses(connection)
        _migrate_attendance_sessions_from_time_entries(connection)
        _migrate_attendance_sessions_add_context_columns(connection)
        _migrate_attendance_sessions_add_admin_close_columns(connection)
        _migrate_scheduling_tables(connection)
        _migrate_work_schedules_schedule_type(connection)
        _migrate_employee_profiles_table(connection)
        _migrate_expenses_tables(connection)
        _reset_identity_sequences(connection)


def _execute_schema(connection) -> None:
    """
    Execute schema statements one by one.

    psycopg does not execute multi-statement schema strings with bound params.
    Splitting keeps initialization explicit and easy to debug.
    """
    for statement in SCHEMA_SQL.split(";"):
        clean_statement = statement.strip()
        if clean_statement:
            connection.execute(clean_statement)


def _table_columns(connection, table_name: str) -> set[str]:
    rows = connection.execute(
        """
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = CURRENT_SCHEMA()
          AND table_name = %s
        """,
        (table_name,),
    ).fetchall()
    return {row["column_name"] for row in rows}


def _migrate_users_saas_columns(connection) -> None:
    """Add SaaS owner-login fields while preserving legacy password users."""
    columns = _table_columns(connection, "users")
    additions = {
        "email": "TEXT",
        "full_name": "TEXT",
        "google_id": "TEXT",
        "auth_provider": "TEXT NOT NULL DEFAULT 'password'",
        "is_active": "BOOLEAN NOT NULL DEFAULT TRUE",
        "updated_at": "TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP",
    }
    for name, definition in additions.items():
        if name not in columns:
            connection.execute(f"ALTER TABLE users ADD COLUMN {name} {definition}")

    if "password_hash" in columns:
        connection.execute("ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL")

    connection.execute(
        """
        UPDATE users
        SET full_name = TRIM(COALESCE(first_name, '') || ' ' || COALESCE(last_name, ''))
        WHERE full_name IS NULL OR TRIM(full_name) = ''
        """
    )
    connection.execute(
        """
        UPDATE users
        SET email = NULLIF(TRIM(email), '')
        WHERE email IS NOT NULL
        """
    )
    connection.execute(
        """
        UPDATE users
        SET is_active = active
        WHERE is_active IS DISTINCT FROM active
        """
    )
    connection.execute(
        """
        UPDATE users
        SET auth_provider = 'password'
        WHERE auth_provider IS NULL OR auth_provider NOT IN ('password', 'google')
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower
        ON users(LOWER(email))
        WHERE email IS NOT NULL
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_users_google_id
        ON users(google_id)
        WHERE google_id IS NOT NULL
        """
    )


def _migrate_platform_user_columns(connection) -> None:
    """Add global platform-admin fields, independent from tenant memberships."""
    columns = _table_columns(connection, "users")
    additions = {
        "platform_role": "TEXT",
        "force_password_change": "BOOLEAN NOT NULL DEFAULT FALSE",
        "last_login_at": "TIMESTAMP WITHOUT TIME ZONE",
        "deactivated_at": "TIMESTAMP WITHOUT TIME ZONE",
    }
    for name, definition in additions.items():
        if name not in columns:
            connection.execute(f"ALTER TABLE users ADD COLUMN {name} {definition}")

    connection.execute(
        """
        UPDATE users
        SET platform_role = NULL
        WHERE platform_role IS NOT NULL
          AND platform_role NOT IN ('superadmin', 'internal_admin')
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_users_platform_role
        ON users(platform_role, active)
        WHERE platform_role IS NOT NULL
        """
    )


def _migrate_business_saas_columns(connection) -> None:
    columns = _table_columns(connection, "businesses")
    additions = {
        "name": "TEXT",
        "timezone": "TEXT NOT NULL DEFAULT 'Europe/Madrid'",
        "country": "TEXT",
    }
    for name, definition in additions.items():
        if name not in columns:
            connection.execute(f"ALTER TABLE businesses ADD COLUMN {name} {definition}")

    connection.execute(
        """
        UPDATE businesses
        SET name = business_name
        WHERE name IS NULL OR TRIM(name) = ''
        """
    )
    connection.execute(
        """
        UPDATE businesses
        SET timezone = 'Europe/Madrid'
        WHERE timezone IS NULL OR TRIM(timezone) = ''
        """
    )


def _migrate_business_platform_columns(connection) -> None:
    columns = _table_columns(connection, "businesses")
    additions = {
        "primary_email": "TEXT",
        "phone": "TEXT",
        "suspended_at": "TIMESTAMP WITHOUT TIME ZONE",
        "suspended_reason": "TEXT",
        "archived_at": "TIMESTAMP WITHOUT TIME ZONE",
    }
    for name, definition in additions.items():
        if name not in columns:
            connection.execute(f"ALTER TABLE businesses ADD COLUMN {name} {definition}")

    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_businesses_platform_status
        ON businesses(is_active, suspended_at, archived_at)
        """
    )


def _migrate_business_users_table(connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS business_users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_id TEXT NOT NULL,
            user_id INTEGER NOT NULL,
            role TEXT NOT NULL
                CHECK (role IN ('owner', 'admin', 'manager', 'employee', 'kiosk_device')),
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('active', 'invited', 'disabled')),
            invited_at TIMESTAMP WITHOUT TIME ZONE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            UNIQUE (business_id, user_id),
            FOREIGN KEY (business_id) REFERENCES businesses(id),
            FOREIGN KEY (user_id) REFERENCES users(id)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_business_users_user
        ON business_users(user_id, status)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_business_users_business
        ON business_users(business_id, role, status)
        """
    )


def _migrate_plans_and_subscriptions(connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS plans (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            max_employees INTEGER NOT NULL,
            max_admins INTEGER NOT NULL,
            has_kiosk BOOLEAN NOT NULL DEFAULT TRUE,
            has_advanced_reports BOOLEAN NOT NULL DEFAULT FALSE,
            has_geolocation BOOLEAN NOT NULL DEFAULT FALSE,
            has_multi_location BOOLEAN NOT NULL DEFAULT FALSE,
            has_exports_basic BOOLEAN NOT NULL DEFAULT TRUE,
            has_exports_advanced BOOLEAN NOT NULL DEFAULT FALSE,
            has_filters_advanced BOOLEAN NOT NULL DEFAULT FALSE,
            has_incident_management BOOLEAN NOT NULL DEFAULT FALSE,
            has_admin_closures BOOLEAN NOT NULL DEFAULT FALSE,
            has_implementation_support BOOLEAN NOT NULL DEFAULT FALSE,
            has_priority_support BOOLEAN NOT NULL DEFAULT FALSE,
            has_custom_branding BOOLEAN NOT NULL DEFAULT FALSE,
            price_monthly NUMERIC(10, 2) NOT NULL DEFAULT 0,
            price_yearly NUMERIC(10, 2) NOT NULL DEFAULT 0,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS subscriptions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_id TEXT NOT NULL UNIQUE,
            plan_id INTEGER NOT NULL,
            status TEXT NOT NULL DEFAULT 'active'
                CHECK (status IN ('trial', 'trialing', 'active', 'past_due', 'paused', 'cancelled', 'canceled', 'expired', 'suspended', 'incomplete')),
            billing_cycle TEXT NOT NULL DEFAULT 'monthly'
                CHECK (billing_cycle IN ('monthly', 'yearly')),
            price NUMERIC(10, 2),
            currency TEXT NOT NULL DEFAULT 'EUR',
            current_period_start TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            current_period_end TIMESTAMP WITHOUT TIME ZONE,
            renewal_date TIMESTAMP WITHOUT TIME ZONE,
            cancel_at TIMESTAMP WITHOUT TIME ZONE,
            cancelled_at TIMESTAMP WITHOUT TIME ZONE,
            trial_ends_at TIMESTAMP WITHOUT TIME ZONE,
            paused_at TIMESTAMP WITHOUT TIME ZONE,
            payment_status TEXT NOT NULL DEFAULT 'none',
            notes TEXT,
            stripe_customer_id TEXT,
            stripe_subscription_id TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (business_id) REFERENCES businesses(id),
            FOREIGN KEY (plan_id) REFERENCES plans(id)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_subscriptions_plan
        ON subscriptions(plan_id, status)
        """
    )
    _migrate_plans_add_feature_columns(connection)
    _migrate_subscription_platform_columns(connection)
    _seed_default_plans(connection)


def _seed_default_plans(connection) -> None:
    # (code, name, max_emp, max_adm, kiosk, adv_rep, geo, multi_loc,
    #  exp_basic, exp_adv, filters_adv, incidents, admin_cls, impl_support,
    #  priority_support, custom_branding, price_monthly, price_yearly)
    plans = (
        ("free", "Free", 1, 1, True, False, False, False, True, False, False, False, False, False, False, False, 0, 0),
        ("basic", "Basic", 3, 2, True, False, False, False, True, False, False, False, False, False, False, False, 9, 90),
        ("pro", "Pro", 30, 10, True, True, True, True, True, True, True, True, True, True, True, False, 29, 290),
        ("enterprise", "Enterprise", 500, 100, True, True, True, True, True, True, True, True, True, True, True, True, 99, 990),
    )
    for plan in plans:
        connection.execute(
            """
            INSERT INTO plans (
                code, name, max_employees, max_admins,
                has_kiosk, has_advanced_reports, has_geolocation, has_multi_location,
                has_exports_basic, has_exports_advanced,
                has_filters_advanced, has_incident_management,
                has_admin_closures, has_implementation_support,
                has_priority_support, has_custom_branding,
                price_monthly, price_yearly
            )
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (code) DO UPDATE SET
                name = EXCLUDED.name,
                max_employees = EXCLUDED.max_employees,
                max_admins = EXCLUDED.max_admins,
                has_kiosk = EXCLUDED.has_kiosk,
                has_advanced_reports = EXCLUDED.has_advanced_reports,
                has_geolocation = EXCLUDED.has_geolocation,
                has_multi_location = EXCLUDED.has_multi_location,
                has_exports_basic = EXCLUDED.has_exports_basic,
                has_exports_advanced = EXCLUDED.has_exports_advanced,
                has_filters_advanced = EXCLUDED.has_filters_advanced,
                has_incident_management = EXCLUDED.has_incident_management,
                has_admin_closures = EXCLUDED.has_admin_closures,
                has_implementation_support = EXCLUDED.has_implementation_support,
                has_priority_support = EXCLUDED.has_priority_support,
                has_custom_branding = EXCLUDED.has_custom_branding,
                price_monthly = EXCLUDED.price_monthly,
                price_yearly = EXCLUDED.price_yearly,
                is_active = TRUE,
                updated_at = CURRENT_TIMESTAMP
            """,
            plan,
        )


def _migrate_employees_saas_columns(connection) -> None:
    columns = _table_columns(connection, "employees")
    additions = {
        "business_id": "TEXT",
        "user_id": "INTEGER",
        "internal_code": "TEXT",
        "pin_code": "TEXT",
        "email": "TEXT",
        "phone": "TEXT",
        "role_title": "TEXT",
        "is_active": "BOOLEAN NOT NULL DEFAULT TRUE",
        "updated_at": "TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP",
    }
    for name, definition in additions.items():
        if name not in columns:
            connection.execute(f"ALTER TABLE employees ADD COLUMN {name} {definition}")

    connection.execute(
        """
        UPDATE employees
        SET user_id = id
        WHERE user_id IS NULL
          AND EXISTS (SELECT 1 FROM users u WHERE u.id = employees.id)
        """
    )
    connection.execute(
        """
        UPDATE employees
        SET internal_code = username
        WHERE internal_code IS NULL OR TRIM(internal_code) = ''
        """
    )
    connection.execute(
        """
        UPDATE employees
        SET is_active = active
        WHERE is_active IS DISTINCT FROM active
        """
    )
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_employees_business_internal_code_active
        ON employees(business_id, LOWER(internal_code))
        WHERE business_id IS NOT NULL AND internal_code IS NOT NULL AND is_active IS TRUE
        """
    )


def _migrate_business_foundation(connection) -> None:
    """Add SaaS business context columns to older local databases."""
    user_columns = _table_columns(connection, "users")
    if "last_business_id" not in user_columns:
        connection.execute("ALTER TABLE users ADD COLUMN last_business_id TEXT")

    session_columns = _table_columns(connection, "attendance_sessions")
    if "business_id" not in session_columns:
        connection.execute("ALTER TABLE attendance_sessions ADD COLUMN business_id TEXT")
    connection.execute("DROP INDEX IF EXISTS idx_attendance_sessions_one_active")
    connection.execute(
        """
        CREATE UNIQUE INDEX IF NOT EXISTS idx_attendance_sessions_one_active
        ON attendance_sessions(COALESCE(business_id, ''), user_id)
        WHERE is_active IS TRUE
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_attendance_sessions_business_clock_in
        ON attendance_sessions(business_id, clock_in_time)
        """
    )

    time_entry_columns = _table_columns(connection, "time_entries")
    if "business_id" not in time_entry_columns:
        connection.execute("ALTER TABLE time_entries ADD COLUMN business_id TEXT")
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_time_entries_business_timestamp
        ON time_entries(business_id, timestamp)
        """
    )


def _migrate_legacy_employee_columns(connection) -> None:
    """
    Keep older databases working after splitting employees.name into
    first_name and last_name.
    """
    columns = _table_columns(connection, "employees")
    had_name_column = "name" in columns

    if "first_name" not in columns:
        connection.execute("ALTER TABLE employees ADD COLUMN first_name TEXT")
    if "last_name" not in columns:
        connection.execute("ALTER TABLE employees ADD COLUMN last_name TEXT")
    if "name" not in columns:
        connection.execute("ALTER TABLE employees ADD COLUMN name TEXT")
    if "created_at" not in columns:
        connection.execute(
            "ALTER TABLE employees ADD COLUMN created_at TIMESTAMP WITHOUT TIME ZONE"
        )

    if had_name_column:
        connection.execute(
            """
            UPDATE employees
            SET first_name = CASE
                    WHEN first_name IS NOT NULL AND TRIM(first_name) <> ''
                        THEN TRIM(first_name)
                    WHEN POSITION(' ' IN TRIM(name)) > 0
                        THEN TRIM(SUBSTRING(TRIM(name) FROM 1 FOR POSITION(' ' IN TRIM(name)) - 1))
                    ELSE COALESCE(NULLIF(TRIM(name), ''), username)
                END,
                last_name = CASE
                    WHEN last_name IS NOT NULL AND TRIM(last_name) <> ''
                        THEN TRIM(last_name)
                    WHEN POSITION(' ' IN TRIM(name)) > 0
                        THEN TRIM(SUBSTRING(TRIM(name) FROM POSITION(' ' IN TRIM(name)) + 1))
                    ELSE ''
                END
            WHERE first_name IS NULL
               OR TRIM(first_name) = ''
               OR last_name IS NULL
            """
        )
    else:
        connection.execute(
            """
            UPDATE employees
            SET first_name = COALESCE(NULLIF(TRIM(first_name), ''), username),
                last_name = COALESCE(last_name, '')
            WHERE first_name IS NULL
               OR TRIM(first_name) = ''
               OR last_name IS NULL
            """
        )

    connection.execute(
        """
        UPDATE employees
        SET name = TRIM(COALESCE(first_name, '') || ' ' || COALESCE(last_name, ''))
        WHERE name IS NULL OR TRIM(name) = ''
        """
    )

    connection.execute(
        """
        UPDATE employees
        SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP)
        WHERE created_at IS NULL
        """
    )


def _migrate_users_from_legacy_employees(connection) -> None:
    rows = connection.execute(
        """
        SELECT id, first_name, last_name, username, password_hash, role, active, created_at
        FROM employees
        ORDER BY id
        """
    ).fetchall()

    for row in rows:
        first_name = (row["first_name"] or row["username"] or "").strip()
        last_name = (row["last_name"] or "").strip()
        dni = (row["username"] or "").strip()
        if not dni:
            continue

        connection.execute(
            """
            INSERT INTO users
                (id, first_name, last_name, dni, password_hash, role, active, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, COALESCE(%s, CURRENT_TIMESTAMP))
            ON CONFLICT DO NOTHING
            """,
            (
                row["id"],
                first_name,
                last_name,
                dni,
                row["password_hash"],
                row["role"],
                row["active"],
                row["created_at"],
            ),
        )


def _ensure_default_admin(connection) -> None:
    admin = connection.execute(
        """
        SELECT id, password_hash
        FROM users
        WHERE LOWER(dni) = LOWER(%s) AND role = 'admin'
        LIMIT 1
        """,
        (DEFAULT_ADMIN_USERNAME,),
    ).fetchone()

    if admin:
        stored_hash = admin["password_hash"]
        if stored_hash and verify_password("admin123", stored_hash) and not verify_password(
            DEFAULT_ADMIN_PASSWORD,
            stored_hash,
        ):
            connection.execute(
                "UPDATE users SET password_hash = %s WHERE id = %s",
                (hash_password(DEFAULT_ADMIN_PASSWORD), admin["id"]),
            )
        return

    connection.execute(
        """
        INSERT INTO users
            (
                first_name, last_name, full_name, dni, password_hash,
                role, active, is_active, auth_provider
            )
        VALUES (%s, %s, %s, %s, %s, 'admin', TRUE, TRUE, 'password')
        """,
        (
            "Admin",
            "Sistema",
            "Admin Sistema",
            DEFAULT_ADMIN_USERNAME,
            hash_password(DEFAULT_ADMIN_PASSWORD),
        ),
    )


def _demote_legacy_default_admin_platform_role(connection) -> None:
    """
    Older builds promoted the default business admin to Superadmin automatically.
    The Superadmin console now has its own bootstrap CLI, so the default admin
    must remain a normal tenant admin and be allowed through /login.
    """
    connection.execute(
        """
        UPDATE users
        SET platform_role = NULL,
            force_password_change = FALSE,
            updated_at = CURRENT_TIMESTAMP
        WHERE LOWER(dni) = LOWER(%s)
          AND role = 'admin'
          AND platform_role IS NOT NULL
        """,
        (DEFAULT_ADMIN_USERNAME,),
    )


def _sync_users_to_legacy_employees(connection) -> None:
    rows = connection.execute(
        """
        SELECT id, first_name, last_name, dni, password_hash, role, active, created_at
        FROM users
        ORDER BY id
        """
    ).fetchall()

    for row in rows:
        if not row["password_hash"]:
            continue
        name = f"{row['first_name']} {row['last_name']}".strip()
        connection.execute(
            """
            INSERT INTO employees
                (id, first_name, last_name, name, username, password_hash, role, active, created_at)
            VALUES (%s, %s, %s, %s, %s, %s, %s, %s, COALESCE(%s, CURRENT_TIMESTAMP))
            ON CONFLICT DO NOTHING
            """,
            (
                row["id"],
                row["first_name"],
                row["last_name"],
                name,
                row["dni"],
                row["password_hash"],
                row["role"],
                row["active"],
                row["created_at"],
            ),
        )
        connection.execute(
            """
            UPDATE employees
            SET first_name = %s,
                last_name = %s,
                name = %s,
                username = %s,
                password_hash = %s,
                role = %s,
                active = %s,
                is_active = %s,
                user_id = COALESCE(user_id, %s),
                internal_code = COALESCE(NULLIF(internal_code, ''), %s),
                created_at = COALESCE(created_at, %s),
                updated_at = CURRENT_TIMESTAMP
            WHERE id = %s
            """,
            (
                row["first_name"],
                row["last_name"],
                name,
                row["dni"],
                row["password_hash"],
                row["role"],
                row["active"],
                row["active"],
                row["id"],
                row["dni"],
                row["created_at"],
                row["id"],
            ),
        )


def _sync_business_members_to_business_users(connection) -> None:
    """Keep the new SaaS membership table populated from legacy memberships."""
    rows = connection.execute(
        """
        SELECT business_id, user_id, member_role, joined_at
        FROM business_members
        """
    ).fetchall()
    for row in rows:
        role = row["member_role"]
        if role not in {"owner", "admin", "employee"}:
            role = "employee"
        connection.execute(
            """
            INSERT INTO business_users
                (business_id, user_id, role, status, created_at)
            VALUES (%s, %s, %s, 'active', COALESCE(%s, CURRENT_TIMESTAMP))
            ON CONFLICT (business_id, user_id) DO UPDATE SET
                role = CASE
                    WHEN business_users.role = 'owner' THEN 'owner'
                    ELSE EXCLUDED.role
                END,
                status = 'active',
                updated_at = CURRENT_TIMESTAMP
            """,
            (row["business_id"], row["user_id"], role, row["joined_at"]),
        )


def _migrate_plans_add_feature_columns(connection) -> None:
    """Add the extended feature-flag columns introduced in the Free/Pro tier split."""
    columns = _table_columns(connection, "plans")
    additions = {
        "has_exports_basic": "BOOLEAN NOT NULL DEFAULT TRUE",
        "has_exports_advanced": "BOOLEAN NOT NULL DEFAULT FALSE",
        "has_filters_advanced": "BOOLEAN NOT NULL DEFAULT FALSE",
        "has_incident_management": "BOOLEAN NOT NULL DEFAULT FALSE",
        "has_admin_closures": "BOOLEAN NOT NULL DEFAULT FALSE",
        "has_implementation_support": "BOOLEAN NOT NULL DEFAULT FALSE",
        "has_priority_support": "BOOLEAN NOT NULL DEFAULT FALSE",
        "has_custom_branding": "BOOLEAN NOT NULL DEFAULT FALSE",
    }
    for col, definition in additions.items():
        if col not in columns:
            connection.execute(f"ALTER TABLE plans ADD COLUMN {col} {definition}")


def _migrate_plans_rename_basic_to_free(connection) -> None:
    """
    Rename the legacy 'basic' plan to 'free' and align its limits/pricing
    to the published Free tier: 0 €/month, max 5 employees.
    Runs idempotently — only updates when the 'basic' code still exists.
    """
    # Kept as a historical migration hook. The SaaS catalog now supports both
    # Free and Basic as separate plans, so this migration must not rewrite Basic.
    return
    connection.execute(
        """
        UPDATE plans
        SET code = 'free',
            name = 'Free',
            max_employees = 5,
            max_admins = 3,
            price_monthly = 0,
            price_yearly = 0,
            updated_at = CURRENT_TIMESTAMP
        WHERE code = 'basic'
        """
    )
    # Align subscriptions that pointed to the old 'basic' plan by name/id
    # (no-op if they already point to the correct plan via FK)


def _migrate_subscription_platform_columns(connection) -> None:
    columns = _table_columns(connection, "subscriptions")
    additions = {
        "billing_cycle": "TEXT NOT NULL DEFAULT 'monthly'",
        "price": "NUMERIC(10, 2)",
        "currency": "TEXT NOT NULL DEFAULT 'EUR'",
        "renewal_date": "TIMESTAMP WITHOUT TIME ZONE",
        "cancel_at": "TIMESTAMP WITHOUT TIME ZONE",
        "cancelled_at": "TIMESTAMP WITHOUT TIME ZONE",
        "trial_ends_at": "TIMESTAMP WITHOUT TIME ZONE",
        "paused_at": "TIMESTAMP WITHOUT TIME ZONE",
        "payment_status": "TEXT NOT NULL DEFAULT 'none'",
        "notes": "TEXT",
    }
    for name, definition in additions.items():
        if name not in columns:
            connection.execute(f"ALTER TABLE subscriptions ADD COLUMN {name} {definition}")

    connection.execute("ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS subscriptions_status_check")
    connection.execute(
        """
        ALTER TABLE subscriptions
        ADD CONSTRAINT subscriptions_status_check
        CHECK (status IN (
            'trial', 'trialing', 'active', 'past_due', 'paused',
            'cancelled', 'canceled', 'expired', 'suspended', 'incomplete'
        ))
        """
    )
    connection.execute("ALTER TABLE subscriptions DROP CONSTRAINT IF EXISTS subscriptions_billing_cycle_check")
    connection.execute(
        """
        ALTER TABLE subscriptions
        ADD CONSTRAINT subscriptions_billing_cycle_check
        CHECK (billing_cycle IN ('monthly', 'yearly'))
        """
    )
    connection.execute(
        """
        UPDATE subscriptions s
        SET price = COALESCE(s.price, p.price_monthly),
            currency = COALESCE(NULLIF(s.currency, ''), 'EUR'),
            billing_cycle = CASE
                WHEN s.billing_cycle IN ('monthly', 'yearly') THEN s.billing_cycle
                ELSE 'monthly'
            END
        FROM plans p
        WHERE p.id = s.plan_id
        """
    )


def _migrate_payment_records_table(connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS payment_records (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_id TEXT NOT NULL,
            subscription_id INTEGER,
            provider TEXT NOT NULL DEFAULT 'internal',
            external_id TEXT,
            amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
            currency TEXT NOT NULL DEFAULT 'EUR',
            status TEXT NOT NULL DEFAULT 'estimated',
            billing_period_start TIMESTAMP WITHOUT TIME ZONE,
            billing_period_end TIMESTAMP WITHOUT TIME ZONE,
            paid_at TIMESTAMP WITHOUT TIME ZONE,
            due_at TIMESTAMP WITHOUT TIME ZONE,
            notes TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (business_id) REFERENCES businesses(id),
            FOREIGN KEY (subscription_id) REFERENCES subscriptions(id)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_payment_records_business
        ON payment_records(business_id, created_at DESC)
        """
    )


def _migrate_audit_logs_table(connection) -> None:
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS audit_logs (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            actor_user_id INTEGER,
            actor_email TEXT,
            action TEXT NOT NULL,
            resource_type TEXT,
            resource_id TEXT,
            business_id TEXT,
            old_value TEXT,
            new_value TEXT,
            metadata TEXT,
            ip_address TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (actor_user_id) REFERENCES users(id),
            FOREIGN KEY (business_id) REFERENCES businesses(id)
        )
        """
    )
    connection.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at DESC)"
    )
    connection.execute(
        "CREATE INDEX IF NOT EXISTS idx_audit_logs_business ON audit_logs(business_id, created_at DESC)"
    )


def _migrate_platform_settings_table(connection) -> None:
    from app.models.platform_settings import PLATFORM_SETTING_DEFAULTS, PLATFORM_SETTING_DESCRIPTIONS

    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS platform_settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            description TEXT,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    for key, value in PLATFORM_SETTING_DEFAULTS.items():
        connection.execute(
            """
            INSERT INTO platform_settings (key, value, description)
            VALUES (%s, %s, %s)
            ON CONFLICT (key) DO NOTHING
            """,
            (key, value, PLATFORM_SETTING_DESCRIPTIONS.get(key)),
        )


def _ensure_subscriptions_for_existing_businesses(connection) -> None:
    # Try 'free' first (post-migration name), fall back to 'basic' (legacy).
    plan = connection.execute(
        "SELECT id FROM plans WHERE code IN ('free', 'basic') ORDER BY price_monthly ASC LIMIT 1"
    ).fetchone()
    if not plan:
        return
    rows = connection.execute("SELECT id FROM businesses").fetchall()
    for row in rows:
        connection.execute(
            """
            INSERT INTO subscriptions (business_id, plan_id, status)
            VALUES (%s, %s, 'active')
            ON CONFLICT (business_id) DO NOTHING
            """,
            (row["id"], plan["id"]),
        )


def _migrate_attendance_sessions_from_time_entries(connection) -> None:
    existing = connection.execute(
        "SELECT COUNT(*) AS count FROM attendance_sessions"
    ).fetchone()["count"]
    if existing:
        return

    rows = connection.execute(
        """
        SELECT employee_id, entry_type, timestamp, notes
        FROM time_entries
        ORDER BY employee_id, timestamp, id
        """
    ).fetchall()

    active_by_user: dict[int, int] = {}
    active_started_at: dict[int, str] = {}

    for row in rows:
        user_id = row["employee_id"]
        entry_type = row["entry_type"]
        timestamp = row["timestamp"]

        user_exists = connection.execute(
            "SELECT 1 FROM users WHERE id = %s",
            (user_id,),
        ).fetchone()
        if not user_exists:
            continue

        if entry_type == "entrada" and user_id not in active_by_user:
            cursor = connection.execute(
                """
                INSERT INTO attendance_sessions
                    (user_id, clock_in_time, is_active, notes)
                VALUES (%s, %s, TRUE, %s)
                RETURNING id
                """,
                (user_id, timestamp, row["notes"]),
            )
            active_by_user[user_id] = int(cursor.fetchone()["id"])
            active_started_at[user_id] = normalize_datetime(timestamp)
            continue

        if entry_type == "salida" and user_id in active_by_user:
            started_at = active_started_at[user_id]
            total_seconds = _seconds_between(started_at, timestamp)
            connection.execute(
                """
                UPDATE attendance_sessions
                SET clock_out_time = %s,
                    is_active = FALSE,
                    total_seconds = %s,
                    notes = COALESCE(notes, %s)
                WHERE id = %s
                """,
                (timestamp, total_seconds, row["notes"], active_by_user[user_id]),
            )
            del active_by_user[user_id]
            del active_started_at[user_id]


def _migrate_attendance_sessions_add_admin_close_columns(connection) -> None:
    """Add admin-close audit columns to attendance_sessions if they don't exist yet."""
    columns = _table_columns(connection, "attendance_sessions")
    if "closed_by_admin" not in columns:
        connection.execute(
            "ALTER TABLE attendance_sessions ADD COLUMN closed_by_admin BOOLEAN NOT NULL DEFAULT FALSE"
        )
    if "manual_close_reason" not in columns:
        connection.execute(
            "ALTER TABLE attendance_sessions ADD COLUMN manual_close_reason TEXT"
        )
    if "closed_by_user_id" not in columns:
        connection.execute(
            "ALTER TABLE attendance_sessions ADD COLUMN closed_by_user_id INTEGER"
        )


def _migrate_attendance_sessions_add_context_columns(connection) -> None:
    """Add exit context columns to attendance_sessions if they don't exist yet."""
    columns = _table_columns(connection, "attendance_sessions")
    if "exit_note" not in columns:
        connection.execute("ALTER TABLE attendance_sessions ADD COLUMN exit_note TEXT")
    if "incident_type" not in columns:
        connection.execute("ALTER TABLE attendance_sessions ADD COLUMN incident_type TEXT")


def _migrate_scheduling_tables(connection) -> None:
    """Add scheduling tables if they don't exist yet (idempotent)."""
    # work_schedules
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS work_schedules (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_id TEXT,
            name TEXT NOT NULL,
            description TEXT,
            weekly_hours_target REAL,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
        )
        """
    )
    work_schedule_columns = _table_columns(connection, "work_schedules")
    if "business_id" not in work_schedule_columns:
        connection.execute("ALTER TABLE work_schedules ADD COLUMN business_id TEXT")
    if "updated_at" not in work_schedule_columns:
        connection.execute(
            "ALTER TABLE work_schedules ADD COLUMN updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP"
        )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_work_schedules_business
        ON work_schedules(business_id, is_active)
        """
    )

    # schedule_days
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS schedule_days (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            schedule_id INTEGER NOT NULL,
            day_of_week SMALLINT NOT NULL,
            start_time TIME WITHOUT TIME ZONE NOT NULL,
            end_time TIME WITHOUT TIME ZONE NOT NULL,
            break_minutes SMALLINT NOT NULL DEFAULT 0,
            late_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
            early_leave_tolerance_minutes SMALLINT NOT NULL DEFAULT 0,
            UNIQUE (schedule_id, day_of_week),
            FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE CASCADE
        )
        """
    )

    # employee_schedules
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS employee_schedules (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            schedule_id INTEGER NOT NULL,
            business_id TEXT,
            effective_from DATE NOT NULL,
            effective_to DATE,
            is_active BOOLEAN NOT NULL DEFAULT TRUE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id),
            FOREIGN KEY (schedule_id) REFERENCES work_schedules(id) ON DELETE RESTRICT
        )
        """
    )
    employee_schedule_columns = _table_columns(connection, "employee_schedules")
    if "business_id" not in employee_schedule_columns:
        connection.execute("ALTER TABLE employee_schedules ADD COLUMN business_id TEXT")
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_employee_schedules_user
        ON employee_schedules(user_id, is_active)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_employee_schedules_schedule
        ON employee_schedules(schedule_id)
        """
    )


def _migrate_work_schedules_schedule_type(connection) -> None:
    """Add schedule_type column to work_schedules if not present."""
    columns = _table_columns(connection, "work_schedules")
    if "schedule_type" not in columns:
        connection.execute(
            """
            ALTER TABLE work_schedules
            ADD COLUMN schedule_type TEXT NOT NULL DEFAULT 'flexible'
            """
        )
    # Enforce CHECK constraint safely (add index for clarity, not hard constraint to stay idempotent)
    connection.execute(
        """
        UPDATE work_schedules
        SET schedule_type = 'flexible'
        WHERE schedule_type NOT IN ('flexible', 'strict')
        """
    )


def _migrate_employee_profiles_table(connection) -> None:
    """Create employee_profiles table if it doesn't exist yet."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS employee_profiles (
            user_id INTEGER PRIMARY KEY,
            hire_date DATE,
            contract_type TEXT,
            department TEXT,
            job_title TEXT,
            phone TEXT,
            personal_email TEXT,
            emergency_contact_name TEXT,
            emergency_contact_phone TEXT,
            social_security_number TEXT,
            notes TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        )
        """
    )


def _migrate_expenses_tables(connection) -> None:
    """Create expenses and expense_attachments tables (idempotent)."""
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS expenses (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            business_id TEXT NOT NULL,
            user_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            amount NUMERIC(10, 2) NOT NULL,
            currency TEXT NOT NULL DEFAULT 'EUR',
            category TEXT NOT NULL DEFAULT 'otros',
            expense_date DATE NOT NULL,
            status TEXT NOT NULL DEFAULT 'pendiente',
            reference_number TEXT,
            admin_notes TEXT,
            reviewed_by INTEGER,
            reviewed_at TIMESTAMP WITHOUT TIME ZONE,
            reimbursed_at TIMESTAMP WITHOUT TIME ZONE,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (business_id) REFERENCES businesses(id),
            FOREIGN KEY (user_id) REFERENCES users(id),
            FOREIGN KEY (reviewed_by) REFERENCES users(id)
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_expenses_business_status
        ON expenses(business_id, status, created_at DESC)
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_expenses_user
        ON expenses(user_id, business_id, created_at DESC)
        """
    )
    connection.execute(
        """
        CREATE TABLE IF NOT EXISTS expense_attachments (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            expense_id INTEGER NOT NULL,
            file_name TEXT NOT NULL,
            file_path TEXT NOT NULL,
            file_size INTEGER,
            mime_type TEXT,
            created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (expense_id) REFERENCES expenses(id) ON DELETE CASCADE
        )
        """
    )
    connection.execute(
        """
        CREATE INDEX IF NOT EXISTS idx_expense_attachments_expense
        ON expense_attachments(expense_id)
        """
    )


def _reset_identity_sequences(connection) -> None:
    for table_name in (
        "users", "employees", "attendance_sessions", "time_entries",
        "work_schedules", "schedule_days", "employee_schedules",
        "business_users", "plans", "subscriptions",
        "expenses", "expense_attachments",
        "payment_records", "audit_logs",
    ):
        connection.execute(
            f"""
            SELECT setval(
                pg_get_serial_sequence('{table_name}', 'id'),
                COALESCE((SELECT MAX(id) FROM {table_name}), 0) + 1,
                FALSE
            )
            """
        )


def _seconds_between(start, end) -> int:
    try:
        started = (
            start if isinstance(start, datetime) else datetime.fromisoformat(str(start))
        )
        ended = end if isinstance(end, datetime) else datetime.fromisoformat(str(end))
    except (TypeError, ValueError):
        return 0
    return max(int((ended - started).total_seconds()), 0)


if __name__ == "__main__":
    initialize_database()
    print("ClockLy database schema is up to date.")
